### ISSUE TITLE
Remove generated wrappers from coreir modules

### ISSUE THREAD

**Issue by leonardt** [phanrahan/mantle#104]
We should define a function to wrap a coreir module (I think @David-Durst already has something similar to this, so maybe we can leverage it) that uses anonymous bits to renamed the `in` and `out` ports to be consistent with the mantle `I` and `O` interface. This will remove the extra "wrapper" modules in the generated code.

**Comment by phanrahan** [comment]
Any chance we could do this before the next hackathon?

**Comment by rdaly525** [comment]
Alternatively, we could extend the coreir c api to access the inline(Instance) function. From the magma backend, you could wrap this however you want, then just call inline.

**Comment by leonardt** [comment]
Added high priority label, should be doable by the next hackathon

**Comment by David-Durst** [comment]
The code where I do port renaming and make anonymous bits is:
https://github.com/phanrahan/magma/blob/master/magma/backend/coreir_.py#L146-L150
and 
https://github.com/phanrahan/magma/blob/master/magma/interface.py#L224-L225

**Comment by leonardt** [comment]
Done by https://github.com/phanrahan/mantle/pull/105/files
