### ISSUE TITLE
Mantle register cannot be properly reset

### ISSUE THREAD

**Issue by Kuree** [phanrahan/mantle#149]
Here is the email sent from Ankita:

--------------------------------------------

So here is the issue we were seeing with the reset for flops that have muxed input. If we simply reset the chip after turning it ON without setting any inputs, the output of the registers are X. As you can see below, during reset, the register does reset to 0, but after reset is low, since out=in, the output becomes X again since the input is X. The input is X since the select to the mux is X and that's X since the inputs to the AND driving it is X. 

 -----------DATA BEFORE RESET -----------

reset signal value = 0

PS register out value = xxxxxxxx

PS register in value = xxxxxxxx

Enable mux sel = x

Mux sel AND input1, 2 and output = x x x

-----------DATA DURING RESET -----------

reset signal value = 1

PS register out value = 00000000

PS register in value = xxxxxxxx

Enable mux sel = x

Mux sel AND input1, 2 and output = x x x

-----------DATA AFTER RESET -----------

reset signal value = 0

PS register out value = xxxxxxxx

PS register in value = xxxxxxxx

Enable mux sel = x

Mux sel AND input1, 2 and output = x x x

Equal logic input1, 2 and output = xx 00 x

The source of this AND gate is ultimately the coreir_eq. That logic compares addr input with a constant value. If this addr input is X, the output of the logic is X. 

So there are two ways to handle this issue. 

1st is connect the EN directly to the register:

module coreir_reg_arst #(parameter arst_posedge=1, parameter clk_posedge=1, parameter init=0, parameter width=1) (

  input clk,

  input arst,

  input en,

  input [width-1:0] in,

  output [width-1:0] out

);

  reg [width-1:0] outReg;

  wire real_rst;

  assign real_rst = arst_posedge ? arst : ~arst;

  wire real_clk;

  assign real_clk = clk_posedge ? clk : ~clk;

  always @(posedge real_clk, posedge real_rst) begin

    if (real_rst) outReg <= init;

    else if (en)  outReg <= in;

    //else outReg <= in; 

  end

  assign out = outReg;

endmodule  // coreir_reg_arst

Other is change the way coreir_eq is done to handle cases when either input is X:

module coreir_eq #(parameter width=1) (

  input [width-1:0] in0,

  input [width-1:0] in1,

  output reg out

);

       always @(in0 or in1) --> NEW

        begin

           if (in0==in1)

              out = 1'b1;

           else

              out = 1'b0;

        end

//  assign out = in0 == in1; --> BEFORE

endmodule  // coreir_eq

 

Both the solutions fix the problem.

-----------DATA BEFORE RESET -----------

reset signal value = 0

PS register out value = xxxxxxxx

PS register in value = xxxxxxxx

Enable mux sel = 0

Mux sel AND input1, 2 and output = 0 0 0

-----------DATA DURING RESET -----------

reset signal value = 1

PS register out value = 00000000

PS register in value = 00000000

Enable mux sel = 0

Mux sel AND input1, 2 and output = 0 0 0

-----------DATA AFTER RESET -----------

reset signal value = 0

PS register out value = 00000000

PS register in value = 00000000

Enable mux sel = 0

Mux sel AND input1, 2 and output = 0 0 0

Equal logic input1, 2 and output = xx 00 0

**Comment by rdaly525** [comment]
We should not change the semantics of coreir_eq. The output should be an 'x' if one of the inputs is an 'x'.

It sounds like possibly the mantle implementation for a synchronous reset needs to take priority over the enable. Would that solve the problem?

**Comment by leonardt** [comment]
Doing reset priority over enable would contradict https://github.com/phanrahan/mantle/pull/139 and https://github.com/phanrahan/mantle/issues/134 which was request by @jeffsetter and supported by others

**Comment by Kuree** [comment]
Unrelated to this issue. 

@jeffsetter actually has a branch in coreir that fixed the similar issue: https://github.com/rdaly525/coreir/tree/fix_mantle

GarnetFlow is actually using this branch to have reset over enable.

**Comment by rdaly525** [comment]
Perhaps having an extra generator argument indicating priority of synchronous reset vs en? It seems like there have been usecases for both.

**Comment by leonardt** [comment]
Added a `reset_priority` parameter (default True) via https://github.com/phanrahan/mantle/pull/150, you can set it to false to use `enable` priority. @ankita0805
