### ISSUE TITLE
Lots of depreciation warnings when using magma.circuit.combinational

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/mantle#178]
Depreciation warnings look something like:

tests/test_alu.py::test_alu
  /Users/rdaly/mantle/mantle/primitives/arith.py:6: DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead
    def DeclareAdd(N, cin=False, cout=False):

tests/test_alu.py::test_alu
  /Users/rdaly/mantle/mantle/primitives/arith.py:50: DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead
    def DeclareSub(N, cin=False, cout=False, T=m.Bits):

tests/test_alu.py::test_alu
  /Users/rdaly/mantle/mantle/coreir/arith.py:84: DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead
    def DefineAdd(N=None, cout=False, cin=False, width=None, T=m.Bits):

tests/test_alu.py::test_alu
  /Users/rdaly/mantle/mantle/coreir/arith.py:127: DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead
    def DefineSub(N, cout=False, cin=False, T=m.Bits):

tests/test_alu.py::test_alu
  /Users/rdaly/mantle/mantle/coreir/LUT.py:10: DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead
    @circuit_generator

**Comment by rsetaluri** [comment]
Thanks @rdaly525...gonna make a pass to clean it all up

**Comment by rsetaluri** [comment]
Resolved by #179. Reopen if more warnings pop up
