### ISSUE TITLE
Mantle generates deprecation warnings

### ISSUE THREAD

**Issue by cdonovick** [phanrahan/mantle#182]
Many primitives generate: 
`DeprecationWarning: circuit_generator decorator is deprecated, subclass Generator instead.`

**Comment by leonardt** [comment]
Hmm, I think this was fixed in #179 but we haven't done a new release yet (grep for circuit_generator inside mantle shows p blank).

I'll trigger a new release, you could also try master to see if that avoids the issue.

**Comment by leonardt** [comment]
2.0.8 released

**Comment by cdonovick** [comment]
New release fixed the warnings.
