### ISSUE TITLE
According to PEP 440 this wildcard syntax is no longer allowed

### ISSUE THREAD

**Issue by jack-melchert** [phanrahan/mantle#198]
https://github.com/phanrahan/mantle/blob/fb8532a87c1bfbf71f664b3bdd0e417614ef0e5e/setup.py#L30

I think changing it to just "fault>=1.0.0" should fix it. 

More info here:
https://github.com/pypa/packaging/issues/645

**Comment by leonardt** [comment]
Fixed by c753957
