### ISSUE TITLE
Minor issues to get coreir->magma working

### ISSUE THREAD

**Issue by rdaly525** [phanrahan/mantle#44]
- [x] DefineCoreirRegister -> DefineCoreirReg. It would be great if all the coreir names can be mapped exactly to DefineCoreir<Uppercasename>
- [x] DefineCoreir<> should take in the exact names of the genparams as arguments. DefineCoreirReg should take in "width" instead of "N"
- [x] Can I have a function called DefineCoreirConst(width, value) which just uses bits(width,value) as its definition?

I am still confused on how to name instances. 
how can I name addinst to be "addinst"
`addinst = mantle.coreir.DefineCoreirAdd(16)`

I am heading into the office now.

Thanks!

**Comment by rdaly525** [comment]
Sorry DefineCoreirConst(width,value) should return a module that has a single port called "out" which is the same semantics as coreir.const

If you dont have time, I can start trying to go through the mantle code to add these functions

**Comment by leonardt** [comment]
1. 5658148
2. d559fc1
3. 0a67212

`mantle.coreir.DefineCoreirAdd(16)` returns a definition, you need to instance it after that and can pass a name then

e.g.

```python
Add16 = mantle.coreir.DefineCoreirAdd(16)
add_inst = Add16(name="add_inst")
```
