### ISSUE TITLE
Resolve == (eq) operator overloading

### ISSUE THREAD

**Issue by leonardt** [phanrahan/mantle#51]
`==` is not implemented because it breaks stuff in the magma internals that use `==` to check for object equality. Offending code should be updated to use `is` instead so we can overload the `==` operator.

**Comment by phanrahan** [comment]
Updating the code to use` is` so we can use `==` would be great.

**Comment by phanrahan** [comment]
Yes, if that error occurs on High Sierra, we should add the note.

**Comment by leonardt** [comment]
Do we want to support `==` on all types? (_Bit, Array, Bits, ...)
