### ISSUE TITLE
Shift Operator TypeError

### ISSUE THREAD

**Issue by adamdai** [phanrahan/mantle#87]
When I am using the `<<` shift operator or `lsl` circuit

```
from magma import *
set_mantle_target("ice40")
from mantle import*

high_byte = bits(0xFF,8)
shifted = high_byte << bits(8,8)
```

Gives `TypeError: FixedLSL() missing 1 required positional argument: 'shift'`. Not sure if wrong syntax or an actual error though.

**Comment by adamdai** [comment]
Also other random question(s), when I try to use LSL to perform a bit shift:
```
high_byte = bits(0xFF,16)
shifted = LSL(16,8)(high_byte)
```
in a python terminal, then look at what shifted is, I get `.O` as an output, as opposed to `bits([1,1,...,0])`. Not sure if this is intended behavior.

Another thing, when working with `bits` types, 
```
b = bits(0xFF,16)
``` 
gives a 16-bit object (i.e. when I ask the terminal for `b` it prints `bits([1,1,...,0])` with 16 entries) but
```
a = bits(0xFF,8)
b = bits(a,16)
```
produces an 8-bit output for `b`.

**Comment by leonardt** [comment]
The TypeError is an issue with our `LSL` interface being inconsistent, that's an implementation bug not syntax error.

`LSL` will construct a shift circuit. If you want to just get the shifted values, you could use a `BitVector(0xFF, 16) << 8` to do that statically (in Python). (You'll need to `from bit_vector import BitVector`)

That `bits` output looks like a bug, can you open a separate issue for that?

**Comment by leonardt** [comment]
ah, that last one is not a bug, I see it now. If you want to extend a, you should use `sext` or `zext` (sign extend or zero extend), or you can use concat. `bits` should just be used for converting the type, not the length.

**Comment by adamdai** [comment]
Oh I see, but in the above syntax with `LSL`, the output of the shift circuit should still be the shifted bits when I run the magma program right?

**Comment by leonardt** [comment]
Yup (you can check this in the simulator)
